## Server properties
spring.main.web-environment=false
#server.port=8080

# Source Debezium properties
traccar.name=traccar-mysql-connector
traccar.datasource.databasename=source_tc
traccar.datasource.host=db-traccar
traccar.datasource.port=3306
traccar.datasource.username=data-cdc
traccar.datasource.password=SzQA9fG0Wkn6Ogxz2Iei97N4
traccar.database.server.id=184054
traccar.include.schema.changes=false
traccar.offset.file=offset/traccar-offset.dat
traccar.history.file=hist/traccar-dbhistory.dat
traccar.database.serverTimezone=UTC
traccar.table.include.list=tc_positions,tc_devices,tc_events,tc_geofences
traccar.message.key.columns=${traccar.datasource.databasename}.tc_positions:id,servertime;${traccar.datasource.databasename}.tc_events:id,eventtime;${traccar.datasource.databasename}.tc_devices:id;${traccar.datasource.databasename}.tc_geofences:id

## Target Database properties
spring.datasource.databasename=target_tc
spring.datasource.url=jdbc:mariadb://db-famous:3306/target_tc
spring.datasource.host=db-famous
spring.datasource.port=3306
spring.datasource.username=adminpanel_tracking
spring.datasource.password=Minergo@2022!
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

## Logging properties
logging.file.name=logs/traccar-cdc.log
logging.file.max-size=100MB
logging.file.max-history=5
logging.level.root=warn
logging.level.org.springframework.web=info
logging.level.org.hibernate=error
logging.level.com.bgs=debug

## Actuator config
#management.endpoints.web.exposure.include=health,metrics
#management.endpoint.health.show-details=always
#management.endpoint.metrics.enabled=true
